### ISSUE TITLE
empty panel

### ISSUE THREAD

**Issue by spyshow** [Maushundb/quick-editor#12]
hii 
i have a problem that when i press ctrl+shift+e ( windows user ) the panel open but it's empty as you can see in the photo 
![1](https://cloud.githubusercontent.com/assets/188788/9975304/e6de16fe-5eb7-11e5-8e60-2ab93d24e4de.jpg)

**Comment by ghost** [comment]
Hello, i have same problem. Any ideas ?

**Comment by spyshow** [comment]
No ... I switched to brackets

**Comment by RenanOliv** [comment]
I haven't tested it on a mac/linux environment but it looks like quick-editor is trying to get the css path file and failing on Windows.

The console throws an error that `cannot read property 'getPath' of null` in the quick-editor.coffee file, [as you can see in the stack trace](http://hastebin.com/esotigayet.tex).

This bug occurred in a Windows 8.1 machine with Atom 1.0.19.

**Comment by Studiomarcoli** [comment]
Same problem here.
Apple OS X Yosemite 10.10.5
Atom 1.10.19

**Comment by Krzyrok** [comment]
I have the same. 
When class (or id) is not defined in css, I have visible pane but with invisible path for adding this undefined selector (moving cursor or other interaction with Atom makes this path visible - but only part by part):
![7eikedb](https://cloud.githubusercontent.com/assets/4472426/10625303/1d1ccfa0-77a2-11e5-8176-36085729a978.png)

When I click 'Add' button, this class/id is added to the CSS - id correctly as #id, but class as \.class:
![css2](https://cloud.githubusercontent.com/assets/4472426/10625532/77720f4a-77a4-11e5-8cee-e3ae9b72ce41.jpg)

If selector was present in CSS, then just empty pane is displayed.

And the worst thing: when I have open empty pane (just after adding new selector using 'Add' button) and I do some changes in CSS (and save it) and I close empty pane (with keyboard shortcut) then all my changes are gone - CSS is reverted to the moment when I added new id/class by 'Add' button in quick edit.

Atom: 1.0.19 with disabled all additional packages (just atom with core packages and your quick-editor)
Windows 8.1

In seetings for your plugin firstly I had empty 'Styles Directory'. Then I tried to specify this. It didn't help.

**Comment by prosf** [comment]
Hello, I had the same problem: When the selector was found in the stylesheet the quick-editor panel opened but was empty.
It seems that it is a css problem.
Mine works okay now by changing the selector:

.quick-editor {
  overflow: hidden;

  atom-text-editor {
    position: absolute;
    width: 100%;
  }
}

to 

.quick-editor {
  overflow: hidden;

  atom-text-editor {
    position: absolute;
    width: 100%;
    height: 100%;
  }
}

in the .atom\packages\quick-editor\styles\quick-editor.less

I haven't set the explicit styles directory ,in the quick-editor settings

**Comment by Krzyrok** [comment]
@prosf thanks, it's working now (after reloading atom) :)

**Comment by prosf** [comment]
That's nice :)
I 'll do a pull request then

**Comment by ProLoser** [comment]
Yup definitely fixes it, thanks @prosf

**Comment by prosf** [comment]
Thanks for committing it ! @ProLoser
