### ISSUE TITLE
Whatever path i give Quick edit doesn't fetch the classes but shows empty

### ISSUE THREAD

**Issue by sparkeplug** [Maushundb/quick-editor#15]
Quick edit is not working.

![screenshot from 2015-12-09 20 09 51](https://cloud.githubusercontent.com/assets/10337388/11688159/f2e526c0-9eb0-11e5-88bb-22af9a6e5277.png)
![screenshot from 2015-12-09 20 10 02](https://cloud.githubusercontent.com/assets/10337388/11688160/f2f00112-9eb0-11e5-8f4c-08890af0428a.png)
![screenshot from 2015-12-09 20 10 11](https://cloud.githubusercontent.com/assets/10337388/11688161/f2f9e0c4-9eb0-11e5-9867-12c4591ad08a.png)

**Comment by Maushundb** [comment]
main.css is not a directory. ..../css/ is the directory. Remove main.css from the path you're giving and it should work.

**Comment by sparkeplug** [comment]
After changing directory as u said, Still the respective css class is not loading in the HTML screen but only an empty space..

![screenshot from 2015-12-11 15 38 13](https://cloud.githubusercontent.com/assets/10337388/11741386/cfba8b08-a01e-11e5-8ddb-42102b475bf7.png)
![screenshot from 2015-12-11 15 38 31](https://cloud.githubusercontent.com/assets/10337388/11741387/cfc650fa-a01e-11e5-97d8-43da3a1aa693.png)
