### ISSUE TITLE
atom-text-editor.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by pepperonas** [Maushundb/quick-editor#23]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
atom-text-editor.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:68:18)
QuickEditorView.getRowElementByLineNumber (/Users/martin/.atom/packages/quick-editor/lib/quick-editor-view.coffee:150:35)
QuickEditorView.setGutterNumbers (/Users/martin/.atom/packages/quick-editor/lib/quick-editor-view.coffee:138:32)
QuickEditorView.attachEditorView (/Users/martin/.atom/packages/quick-editor/lib/quick-editor-view.coffee:93:12)
Object.edit (/Users/martin/.atom/packages/quick-editor/lib/quick-editor.coffee:119:35)
<unknown> (/Users/martin/.atom/packages/quick-editor/lib/quick-editor.coffee:74:28)
```

**Comment by ovictoraurelio** [comment]
Give me this error on open Application, Atom at MAC.

> atom-text-editor.Object.defineProperty.get - /Users/viitra/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:68:18
QuickEditorView.getRowElementByLineNumber - /Users/viitra/.atom/packages/quick-editor/lib/quick-editor-view.coffee:150:35
QuickEditorView.setGutterNumbers - /Users/viitra/.atom/packages/quick-editor/lib/quick-editor-view.coffee:138:32
QuickEditorView.attachEditorView - /Users/viitra/.atom/packages/quick-editor/lib/quick-editor-view.coffee:93:12
Object.edit - /Users/viitra/.atom/packages/quick-editor/lib/quick-editor.coffee:119:35
<unknown> - /Users/viitra/.atom/packages/quick-editor/lib/quick-editor.coffee:74:28

>
