### ISSUE TITLE
Shortcuts for switching to the quick editor and closing it

### ISSUE THREAD

**Issue by amannn** [Maushundb/quick-editor#4]
In your video it seems as if you can close the editor with some kind of shortcut. How do you do that?

And is there a way to bring the focus to the quick editor without using the mouse?

Thanks!

**Comment by Maushundb** [comment]
Hi! The same shortcut that is used to open the editor will also close it as well.

And unfortunately no there is not a way to focus the editor without a mouse that I know of, but making it autofocus upon opening is on my TODO list so expect that to be out in the new few weeks.

**Comment by amannn** [comment]
Great, thanks!
