### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by astromac** [Maushundb/quick-editor#7]
I assume it's a conflict with another package but hover the cursor over a class and pressing the keyboard shortcut does nothing.

Is there anything I can provide you with to help you debug?

**Comment by Maushundb** [comment]
Are you on Windows or Mac? If you're on windows trying changing the your kekboard shortcut to shift-ctrl-e instead in your keymap file.

**Comment by camjc** [comment]
You can see what is bound to any keypress with the keybinding resolver.
Packages menu -> Keybinding Resolver -> Toggle.
